version: '3.7'

services:
  web:
    image: ${DOCKER_REGISTRY-}cuweb
    container_name: cuweb
    depends_on:
      - "db"
    build:
      context: .
      dockerfile: ContosoUniversity/Dockerfile
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - webvolume
    networks:
      - cunetwork
    ports:
      - "59075:80"
      - "44367:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44367
  db:
    image: mcr.microsoft.com/mssql/server
    container_name: cudb
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: <YourStrong!Passw0rd>
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume
    networks:
      - cunetwork

networks:
  cunetwork:
    name: cunetwork

volumes:
  sqlvolume:
    name: sqlvolume
  webvolume:
    name: webvolume