receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'prometheus-metrics'
          metrics_path: /metrics
          scrape_interval: 15s
          static_configs:
            - targets: ['host.docker.internal:10000']

exporters:
  otlp_grpc:
    endpoint: ${env:OTEL_EXPORTER_OTLP_ENDPOINT}
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [otlp_grpc]
