global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: contoso-mvc
    static_configs:
      - targets:
          - 'web:80'
          - 'host.docker.internal:10000'
remote_write:
  - url: "http://dashboard:4318/otlp/v1/metrics"
    protobuf_message: "io.prometheus.write.v2.Request"
    tls_config:
      insecure_skip_verify: true
